import { GetStaticProps } from "next";
import { StaticProps } from "../../content/entities";
import { StyledMain } from "../../components/Layout/components/Main/main.styles";
import { ReleasesView } from "../../views/ReleasesView/releasesView";
import { FRONTMATTER } from "../../views/ReleasesView/frontmatter";
import { Release } from "../../views/ReleasesView/types";
import { resolveRelativeDirs } from "@databiosphere/findable-ui/lib/utils/mdx/files/resolveRelativeDirs";
import { format, formatDistanceToNowStrict, compareDesc } from "date-fns";
import { OutlineItem } from "@databiosphere/findable-ui/lib/components/Layout/components/Outline/types";
import slugify from "slugify";
import { buildMDXFilePath } from "@databiosphere/findable-ui/lib/utils/mdx/staticGeneration/utils";
import { getMatter } from "@databiosphere/findable-ui/lib/utils/mdx/frontmatter/getMatter";
import { mapMDXSlugByFilePaths } from "@databiosphere/findable-ui/lib/utils/mdx/files/mapMDXSlugByFilePaths";
import { ROUTES } from "../../routes/constants";

const DOCS_DIR = "docs";
const RELEASES_DIR = "releases";

export interface PageProps
  extends Omit<StaticProps, "layoutStyle" | "mdxSource"> {
  releases: Release[];
}

const Page = (props: PageProps): JSX.Element => {
  return <ReleasesView {...props} />;
};

export const getStaticProps: GetStaticProps<PageProps> = async () => {
  const pathsByDate = getDatePathsMap(getDataReleaseSlugs());
  const dates = getReleaseDates(pathsByDate);
  const outline = buildOutline(dates);
  const releases = buildReleases(dates, pathsByDate);
  return {
    props: {
      frontmatter: FRONTMATTER,
      outline,
      pageTitle: "Releases",
      releases,
      slug: [RELEASES_DIR],
    },
  };
};

Page.Main = StyledMain;

export default Page;

/**
 * Returns the outline.
 * @param dates - Release dates.
 * @returns outline.
 */
function buildOutline(dates: Date[]): OutlineItem[] {
  return dates.map((date) => ({
    depth: 1,
    hash: getReleaseId(date),
    value: format(date, "MMMM yyyy"),
  }));
}

/**
 * Returns the releases.
 * @param dates - Release dates.
 * @param pathsByDate - Paths keyed by date.
 * @returns releases.
 */
function buildReleases(
  dates: Date[],
  pathsByDate: Map<Date, string[]>
): Release[] {
  return dates.map((date) => {
    return {
      id: getReleaseId(date),
      month: format(date, "MMMM"),
      timeSinceRelease: formatDistanceToNowStrict(date),
      url: getDatePath(pathsByDate.get(date) ?? []),
      year: format(date, "yyyy"),
    };
  });
}

/**
 * Returns the date path.
 * @param slug - Release slug.
 * @returns date path.
 */
function getDatePath(slug: string[]): string {
  if (!slug.length) return ROUTES.RELEASES;
  return `${ROUTES.RELEASES}/${slug.join("/")}`;
}

/**
 * Returns the date to paths map.
 * @param slugs - Release slugs.
 * @returns date to paths map.
 */
function getDatePathsMap(slugs: string[][]): Map<Date, string[]> {
  return new Map(slugs.map((slug) => [mapReleaseDate(slug), slug]));
}

/**
 * Returns the slugs for each data release.
 * @returns slugs for each data release.
 */
function getDataReleaseSlugs(): string[][] {
  return [
    ...mapMDXSlugByFilePaths(
      resolveRelativeDirs([DOCS_DIR, RELEASES_DIR])
    ).values(),
  ];
}

/**
 * Returns the release dates, sorted in descending order.
 * @param pathsByDate - Paths keyed by date.
 * @returns release dates.
 */
function getReleaseDates(pathsByDate: Map<Date, string[]>): Date[] {
  return [...pathsByDate.keys()].sort(compareDesc);
}

/**
 * Returns the release date.
 * Throws error if no date is found in frontmatter.
 * @param segments - Segments.
 * @returns release date.
 */
function mapReleaseDate(segments: string[]): Date {
  const fileName = buildMDXFilePath([DOCS_DIR, RELEASES_DIR], segments);
  const { data } = getMatter(fileName!); // asserting non-null, filename generated by mapMDXSlugByFilePaths and therefore exists.
  if (!data.date) throw new Error(`Date not found in frontmatter: ${fileName}`);
  return new Date(data.date);
}

/**
 * Returns the release id.
 * @param date - Release date.
 * @returns release id.
 */
function getReleaseId(date: Date): string {
  return slugify(format(date, "MMMM yyyy"), { lower: true, strict: true });
}
