export const ROUTES = {
  ANVIL_CHAMPIONS: "/anvil-champions",
  CONSORTIA: "/consortia",
  EVENTS: "/events",
  FAQ: "/faq",
  GUIDES: "/guides",
  HELP: "/help",
  LEARN: "/learn",
  NEWS: "/news",
  OVERVIEW: "/overview",
  PRIVACY: "/privacy",
  RELEASES: "/releases",
  SEARCH: "/search",
  TEAM: "/team",
};
