# CHANGE THESE VALUES TO GENERATE NEW REPORTS
START_DATE = "2024-11-26"
END_DATE = "2024-12-26"
PARENT_FOLDER_NAME = "December 2024 (demos)"

ANVIL_PORTAL_NAME = "anvil-portal"
ANVIL_CATALOG_NAME = "anvil-catalog"
ANVIL_EXPLORER_NAME = "anvil-explorer"

PROPERTY_ID_MAP = {
    ANVIL_CATALOG_NAME: "368661710",
    ANVIL_EXPLORER_NAME: "383267328",
    ANVIL_PORTAL_NAME: "368678391",
}

SECRET_NAME = 'ANVIL_ANALYTICS_REPORTING_CLIENT_SECRET_PATH'
GA_PROPERTY_PORTAL = "368678391" # AnVIL Portal - GA4
PRE_AUDIENCE_EXCLUDE_PAGES_FILTER = "landingPagePlusQueryString!=/guides/content/creating-links"
EXCLUDE_PAGES_FILTER = {"filter": {"fieldName": "audienceId", "numericFilter": {"operation": "EQUAL", "value": {"doubleValue": 5559548544}}}}
ANALYTICS_START = "2021-01-01"

OAUTH_PORT = 8082