name: Test build
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20.10.0"
      
      - run: |
          npm ci
          npx tsc --noEmit
          npm run build-dev:anvil-portal
